### ISSUE TITLE
bitcoin icon not accessible in 0.0.9 

### ISSUE THREAD

**Issue by pavanjoshi914** [uxthings/popicons#2]
there is no bitcoin icon export in popicons/react package in newer version. it was in earlier version

**Comment by reneaaron** [comment]
Also some other newer icons seem to be missing in the npm package currently. @filipgrkinic Is there a chance you can update that anytime soon? :hugs:

**Comment by filipgrkinic** [comment]
@pavanjoshi914 @reneaaron 

I've added all new icons. Will also make sure to update these more often here, as new ones get added.

**Comment by filipgrkinic** [comment]
@pavanjoshi914 @reneaaron

I've added all new icons. Will also make sure to update these more often here, as new ones get added.

**Comment by pavanjoshi914** [comment]
Thanks a lot! waiting for the popicons next release :rocket:
