### ISSUE TITLE
site seems to be broken

### ISSUE THREAD

**Issue by pavanjoshi914** [uxthings/popicons#3]
![image](https://github.com/uxthings/popicons/assets/55848322/56e796f9-f4a2-48b7-b700-15490010d170)

no icons i can see on https://popicons.cc/icons

**Comment by filipgrkinic** [comment]
@pavanjoshi914 is it still broken? works on my end

**Comment by pavanjoshi914** [comment]
It works currently but it's been more than twice. I experienced the same
issue. Where site loading fails

**Comment by filipgrkinic** [comment]
Site is consuming new API since today, I'll close this for now but let me know if it keeps happening.

**Comment by pavanjoshi914** [comment]
![image](https://github.com/uxthings/popicons/assets/55848322/a29702ca-7135-44c4-82a0-57c337037f4d)

it's still broken
