### ISSUE TITLE
@popicons/react-native doesn't work

### ISSUE THREAD

**Issue by im-adithya** [uxthings/popicons#4]
Firstly, thanks for the clean set of icons 🙌 

Coming to the issues,

- The icons are typed as `PopiconsHomeStyleDuotone`, `PopiconsHomeStyleSolid`, `PopiconsHomeStyleLine` etc. in `popicons.d.ts` but are exported as `PopiconsHomeDuotone`, `PopiconsHomeSolid`, `PopiconsHomeLine` etc. in `popicons.js` in the npm package. This is leading to `undefined` errors as TS is forcing to import `PopiconsHomeStyleLine` but it doesn't actually exists. Importing `PopiconsHomeLine` works but it gives a TS error 😄 
- Also it gives `Property 'React' doesn't exist` error even after importing `PopiconsHomeLine` instead of `PopiconsHomeStyleLine` which was resolved after adding `import React from 'react';` in `popicons.js` (or maybe you are running an older version of React?)

Would be great if you can have a look!

**Comment by filipgrkinic** [comment]
@im-adithya thanks for bringing this up, it was indeed a typo in the build process, just published an update:
https://www.npmjs.com/package/@popicons/react-native

**Comment by filipgrkinic** [comment]
@im-adithya thanks for bringing this up, it was indeed a typo in the build process, just published an update:
https://www.npmjs.com/package/@popicons/react-native

**Comment by im-adithya** [comment]
Awesome, thanks!

I tried this just now and I still failed to get this working, I get this error, importing React should fix this issue

And a small nit, I think you missed `PopiconsCircleExclamationLine` (didn't check the rest) 😅 

<table>
<tr>
<td>
<img src="https://github.com/user-attachments/assets/ffff2cc1-0407-4331-bb8d-edabc014c7f3" width="200px"/>
</td>
<td>
<img src="https://github.com/user-attachments/assets/3e25c824-35d5-4409-a3e2-1eb4b19a0363"/>
</td>
</tr>
</table>
