### ISSUE TITLE
@popicons/react-native width prop does not work

### ISSUE THREAD

**Issue by im-adithya** [uxthings/popicons#6]
The props are always applied on the top which makes the default width and height (set to 20) always override the prop width and height

```js
export function PopiconsChevronRightSolid(props) {
  return React.createElement(
    Svg,
    {
      ...props,
      xmlns: "http://www.w3.org/2000/svg",
      width: "20",
      height: "20",
      viewBox: "0 0 20 20",
      fill: "none",
      // ...props should be here
    },
    React.createElement(Path, {
      fillRule: "evenodd",
      clipRule: "evenodd",
      d: "M6.79289 15.7071C6.40237 15.3166 6.40237 14.6834 6.79289 14.2929L11.0858 10L6.79289 5.70711C6.40237 5.31658 6.40237 4.68342 6.79289 4.29289C7.18342 3.90237 7.81658 3.90237 8.20711 4.29289L13.2071 9.29289C13.5976 9.68342 13.5976 10.3166 13.2071 10.7071L8.20711 15.7071C7.81658 16.0976 7.18342 16.0976 6.79289 15.7071Z",
      fill: "currentColor",
    }),
  );
}
```

@filipgrkinic @zaydek can you please look into this?

**Comment by zaydek** [comment]
@im-adithya I'm not able to repro using web/CSS. Is this issue specific to React Native?

**Comment by im-adithya** [comment]
Yes, I'm facing this error in RN

I tried doing `< PopiconsChevronRightSolid  width={60} height={60}/>` but it still stays in 20 width, changing the `...props` to bottom worked.

**Comment by zaydek** [comment]
OK. But in RN would you typically use a stylesheet instead? Like:

```tsx
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  icon: {
    width: 64,
    height: 64,
  },
});

...

<Icon style={styles.icon} />
```

**Comment by im-adithya** [comment]
We are using nativewind (RN's tailwind) so that we can use React-like syntax, so we don't use stylesheets (for example: https://github.com/getAlby/go/blob/master/pages/Transaction.tsx)

**Comment by zaydek** [comment]
I see. Thanks for clarifying. Would it work to use className="w-[60px] h-[60px]"? I see for example in the code `<X className="text-destructive" width={100} height={100} />` so it's probably just a habit that you're using attributes instead. I'm not working on this library ATM so the best I can recommend is try using classes or something like the stylesheet pattern mentioned above.

**Comment by filipgrkinic** [comment]
> The props are always applied on the top which makes the default width and height (set to 20) always override the prop width and height

hey @im-adithya, got it, makes sense! i'll update in a few days.

**Comment by im-adithya** [comment]
> ```
> const styles = StyleSheet.create({
>   icon: {
>     width: 64,
>     height: 64,
>   },
> });
> 
> ```
> 

> className="w-[60px] h-[60px]"?

Both won't work (also tried) since the default attributes are given highest priority. Thanks for the helping though :)

> hey @im-adithya, got it, makes sense! i'll update in a few days.

Awesome, thanks! Can you also have a look at #5, it can be fixed by doing `global.React = React` but would be cool if it is imported within the package itself

**Comment by im-adithya** [comment]
Hey @filipgrkinic any update?

**Comment by filipgrkinic** [comment]
hey @im-adithya just published an update, let me know if that worked

**Comment by filipgrkinic** [comment]
hey @im-adithya just updated, let me know if that worked

**Comment by filipgrkinic** [comment]
> Can you also have a look at #5, it can be fixed by doing `global.React = React` but would be cool if it is imported within the package itself

this should be fixed now as well

0.0.20 :)

**Comment by im-adithya** [comment]
Works great! Thanks Filip 🙌

**Comment by filipgrkinic** [comment]
@im-adithya happy to hear & thanks for a great suggestion!
